#!/usr/bin/python

import RPi.GPIO as GPIO
import time
import smtplib
from email.MIMEMultipart import MIMEMultipart 
from email.MIMEImage import MIMEImage 
from email.MIMEText import MIMEText 
from email.Utils import COMMASPACE, formatdate 
from email import Encoders 
import subprocess
def sendEmail():
  grab_cam = subprocess.Popen("sudo fswebcam -r 640x472 image1.jpg", shell=True)
  grab_cam.wait()  
  image_path = 'image1.jpg'
  username = "deneme@gmail.com"    # arkadaslar mail adreslerini degistirmeyi unutmayiniz :)
  password = "123456"
  COMMASPACE = ','
  message = MIMEMultipart()
  message['Subject'] = 'Hareket Algilandi'
  me = 'info@mustafaergul.com.tr'               # arkadaslar mail adreslerini degistirmeyi unutmayiniz :)
  receivers= 'info@mustafaergul.com.tr'
  message['From'] = me
  message['To'] = COMMASPACE.join(receivers)
  message.preamble = 'Hareket'
  fp = open('image1.jpg', 'rb')
  img = MIMEImage(fp.read())
  fp.close()
  message.attach(img)
  try:
    server = smtplib.SMTP("smtp.gmail.com", 587) #portu mail servis saglayaciniza gore degistirirsiniz.
    server.ehlo()
    server.starttls()
    server.login(username,password)
    server.sendmail(me, receivers.split(","), message.as_string())
    server.close()
    print 'mail gonderildi'
  except:
    print "mail gonderilemedi"

GPIO.setmode(GPIO.BCM)

GPIO_PIR = 7
print "Hareket Modulu Test Ediliyor (cikmak icin CTRL-C)"

GPIO.setup(GPIO_PIR,GPIO.IN)      # Echo

Current_State  = 0
Previous_State = 0

try:

  print "Hareket Sensörü Çalışmak için hazır..."

  while GPIO.input(GPIO_PIR)==1:
    Current_State  = 0    

  print "  Hazir"     
    
  while True :
   
    # Hareket Sensörünün Çalışma Algoritması
    Current_State = GPIO.input(GPIO_PIR)
   
    if Current_State==1 and Previous_State==0:
      print "  Hareket Algilandi!"	 
      sendEmail()
      Previous_State=1
    elif Current_State==0 and Previous_State==1:
      print "  Hazir"
      Previous_State=0
      
    time.sleep(0.01)      
      
except KeyboardInterrupt:
  print "  Cikis" 
  GPIO.cleanup()
